#!/usr/bin/env sh

export from_addr=$1
export to_addr=$2

if [ -z $from_addr -o -z $to_addr ]; then
  echo "Usage: ${0} from_email to_email"
  exit 1
fi

git filter-branch --env-filter '

an="$GIT_AUTHOR_NAME"
am="$GIT_AUTHOR_EMAIL"
cn="$GIT_COMMITTER_NAME"
cm="$GIT_COMMITTER_EMAIL"

if [ "$GIT_COMMITTER_EMAIL" = "$from_addr" ]; then
  cm="$to_addr"
fi

if [ "$GIT_AUTHOR_EMAIL" = "$from_addr" ]; then
  am="$to_addr"
fi

export GIT_AUTHOR_NAME="$an"
export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_NAME="$cn"
export GIT_COMMITTER_EMAIL="$cm"
'
